import com.singularity_universe.axon.Axon
import com.singularity_universe.axon.exception.ResolverException
import com.singularity_universe.axon.generated.init
import com.singularity_universe.axon.utils.Log
import intent.DeleteAccountIntent
import intent.LoginIntent
import intent.LogoutIntent
import kotlinx.coroutines.runBlocking

fun main() {
    runBlocking {
        val axon = Axon()
        axon.init() // generated by KSP — all @Resolve resolvers wired automatically

        when (val result = axon.dispatch(LoginIntent(data = LoginIntent.LoginData(username = "steve", password = "secret"), parent = null))) {
            is LoginIntent.LoginResult.LoginSuccess -> println("login success: ${result.token}")
            is LoginIntent.LoginResult.LoginBlocked -> println("login blocked")
            is LoginIntent.LoginResult.UnableToProcess -> println("unable to process")
        }

        val logoutResult = axon.dispatch(LogoutIntent(userId = "user-123", parent = null))
        println("logout success: ${logoutResult.success}")

        try {
            axon.dispatch(DeleteAccountIntent(userId = "user-123", parent = null))
        } catch (e: ResolverException) {
            Log.error("Resolver bug caught by caller: ${e.message}")
        }
    }
}
